### ISSUE TITLE
outdated lib?

### ISSUE THREAD

**Issue by tonisvain** [oeklo/gsmtasks-completed-error#1]
Got the project installed.

in order to get the `poetry install` to work, i had to change the **gsmtasks-client** resolved_reference from resolved_reference from **2abc40749e70254128e092240e1bfb7566ef7928** to  **99dea1aaef1c370c679b7daee26660c7f299981d**
hope this didn't mess anything up, but i could not install it with the old reference

```
[package.source]
type = "git"
url = "https://github.com/oeklo/gsmtasks-client.git"
reference = "develop"
resolved_reference = "99dea1aaef1c370c679b7daee26660c7f299981d"
```

When running the code, i get this error:

```
  File "/Users/tonisvain/Downloads/000_gsmtasks-completed-error-main/src/gsmtasks_complete/__main__.py", line 27, in main
    client = ApiClient(token)
  File "/Users/tonisvain/Library/Caches/pypoetry/virtualenvs/gsmtasks-complete-LEWtKOr_-py3.10/lib/python3.10/site-packages/gsmtasks/client.py", line 346, in __init__
    self.auth_tokenAuth = lapidary_base.HTTPAuth(
AttributeError: module 'lapidary_base' has no attribute 'HTTPAuth'
```

**Comment by rafalkrupinski** [comment]
Sorry, the dependency was on the develop branch, and that project has moved on since.
I've put the latest version there,

**Comment by tonisvain** [comment]
just to keep the conversation going:

The issue is, that when completing a task and fetching the task directly, the values have updated, but when filtering the list, the freshly completed task on not in the list.

am i correct?

**Comment by rafalkrupinski** [comment]
@tonisvain yep

**Comment by tonisvain** [comment]
Hey. 

Found the issue. 
Will let you know what we can do about it. 

it was some fix for an issue we had 6 years ago.
Basically what happens id that filtering with `updated_at__gt(e)=xxxx` automatically bounds the updated_at end also. 
so a quick hack would be to set another filter `updated_at__lte=pendulum.now().add(seconds=1)` whenever filtering with updated_at.

sorry for the inconvenience.

**Comment by rafalkrupinski** [comment]
@tonisvain 
Please, please, please, put it in the API documentation :)
Is it just the case with tasks or other resources as well?

**Comment by tonisvain** [comment]
Hey. 

We made a solution for this issue in API version 2.4.13. 
Filtering with `updated_at` should no longer present any unexpected issues. 
The same issue was present on the other endpoints that used `updated_at` filters also.

The change is reflected in the documentation.

**Comment by rafalkrupinski** [comment]
@tonisvain
[continued](#2)
